[tool.poetry]
name = "simulation-toolbox"
version = "0.1.0"
description = ""
authors = ["Cristobal Rodero <cristobal.rodero@imperial.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.13"
gsa-library = {git = "https://github.com/MarinaStrocchi/GSA_library.git"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
