[tool.poetry]
name = "simulation-toolbox"
version = "0.1.0"
description = ""
authors = ["Cristobal Rodero <cristobal.rodero@imperial.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~=3.9.13"
simulation-library = {git = "ssh://git@github.com/MarinaStrocchi/SIMULATION_library.git", rev = "developer"}
requests = "^2.31.0"
scipy = "1.7.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
